services:
  # API Service
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: h2-api
    ports:
      - "8050:8080"
      - "8051:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - h2-network

  # Blazor WASM App
  blazor:
    build:
      context: .
      dockerfile: Blazor/Dockerfile
    container_name: h2-blazor
    ports:
      - "8052:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_ENDPOINT_DOCKER=http://api:8080/
      - API_ENDPOINT_LOCAL=http://localhost:5253/
      - API_ENDPOINT_PRODUCTION=https://h2-api.mercantec.tech/
    depends_on:
      - api
    networks:
      - h2-network

networks:
  h2-network:
    driver: bridge 